server {
    listen 443 ssl;
    server_name web-p2.test 10.23.88.130;

    ssl_certificate /etc/nginx/ssl/web-p2.crt;
    ssl_certificate_key /etc/nginx/ssl/web-p2.key;
    ssl_protocols TLSv1.2 TLSv1.3;

    root /var/www/p2;
    index index.php;

    access_log /var/log/nginx/p2-access.log;
    error_log /var/log/nginx/p2-error.log;

    location / {
        try_files $uri $uri/ =404;
    }

    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/run/php/php8.3-fpm.sock;
    }

    location ~ /\. {
        deny all;
    }
}
